### ISSUE TITLE
Question on portability - Android/iOS

### ISSUE THREAD

**Issue by pliablepixels** [pbakondy/filelogger#1]
Hello, thank you  for this lovely plugin.

A quick side note:
The plugin for cordova is now called cordova-plugin-file so you may want to modify your note as 

```
cordova plugin add cordova-plugin-file
```

Now to my question: Have you by any chance  tested if this works on Android as well across various devices? I have limited access to android devices and am hoping I can use the log file to debug problems if users report them.

I love it that your plugin does not make me have to worry about file paths etc. I am hoping it abstracts correctly for android as well :+1: 

Thanks again

**Comment by pbakondy** [comment]
I fixed the plugin name to cordova-plugin-file.

To answer your question, yes, this plugin is tested and used on various Android devices.
It works as expected.
