### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by pliablepixels** [pbakondy/filelogger#2]
Hello is there a portable way to get file size? I'd like to delete the file if it exceeds a particular limit to manage space.

**Comment by pbakondy** [comment]
tada.wav
check README

**Comment by pliablepixels** [comment]
Awesome! works great. I noticed you wrapped everything in timeouts. Is that recommended? I am calling your functions after the device is ready and have not wrapped in timeouts.

**Comment by pbakondy** [comment]
You mean timeouts in the example code?
File writings are asynchronous command. Timeout are for waiting to finish file actions.
If you use only the log writer methods you don't have to use timeout.

**Comment by pliablepixels** [comment]
thanks. why do we need timeouts when they return promises?

**Comment by pbakondy** [comment]
It is just easier to read the example code.
You can use promises as well.

**Comment by pliablepixels** [comment]
I see. Thanks again.
