### ISSUE TITLE
Error with Ripple Emulator

### ISSUE THREAD

**Issue by zazics** [pbakondy/filelogger#30]
I tried to user $filelogger in an Ionic project. Ripple Emulator is sometimes used during development process. But my application complains about "missing exec:File.resolveLocalFileSystemURI".
![ripple](https://cloud.githubusercontent.com/assets/6505940/18910176/1bb421ac-8577-11e6-9a30-55efc99751db.png)

Filelogger plugin don't need to fully support Ripple environment but is it possible to switch correctly to console.log() in that case ?

**Comment by pbakondy** [comment]
The plugin already writes to console.log

I dont know the Ripple tool.
Could you provide a little example code to try and fix this issue?

**Comment by zazics** [comment]
Ripple is commonly used in Ionic app under Visual Studio. With it, you can fastly modify your code and deploy your app onto a "pseudo" mobile emulator.
Here is the Ripple Emulator: https://www.npmjs.com/package/ripple-emulator

I suppose that your plugin switch to "console.log()" based on the existence of "cordova".
The problem with Ripple is that it **partially** implement Cordova. It means that "cordova" and "cordova.file" objects exist but not all sub functions like "resolveLocalFileSystemURI".
Maybe you can check the existence of mandatory sub functions like this one ?

**Comment by pbakondy** [comment]
"The Ripple podling retired on 2015-12-06" ( from https://incubator.apache.org/projects/ripple.html )

I can exclude running filelogger in "cordova mode" when ripple environment is detected.

Can you help me to detect ripple? For example does exist `window.ripple` or any similar object?

**Comment by zazics** [comment]
Here is how I detect Ripple environment:

 this.isRippleMode = function ()
        {
            if (cordova)
            {
                var exec = cordova.require('cordova/exec');
                if (exec.toString().indexOf("emulator") > 0)
                {
                    return true;
                }
            }
            return false;
        };

**Comment by pbakondy** [comment]
Please test latest version (v1.3.2)

**Comment by zazics** [comment]
Done. 
Great job! :+1: 
Thanks.
