### ISSUE TITLE
Where is my log file stored in my device?

### ISSUE THREAD

**Issue by chaitrahegde** [pbakondy/filelogger#33]
I am using this module for debug and logging errors when running my ionic app in my android device. I would like to access this file at a later stage for reading. Could you please let me know where is this file stored in my android device and how I could have access to it? Thanks in advance.

**Comment by pbakondy** [comment]
The location is `cordova.file.dataDirectory`.
Docs: http://ngcordova.com/docs/plugins/file/#android-file-system-layout

**Comment by saberprashant** [comment]
Hi @chaitrahegde @pbakondy ,
I tried to find out the stated path to read the log file, but I didn't find out any directory with such name. Please help me, I really want to read the logs.
PS: The logs are visible in Local storage when I run my app in browser.

Thanks.
